/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import FormBolnica.FormNovaBolnica;
import FormBolnica.FormPretragaBolnica;
import FormPorudzbina.FormPretragaPorudzbine;
import controller.ClientController;
import domain.Administrator;
import domain.KategorijaMedicinskogSredstva;
import domain.Bolnica;
import domain.MedicinskoSredstvo;
import domain.Porudzbina;
import domain.StavkaPorudzbine;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavke;
import session.Session;

/**
 *
 * @Korisnik
 */
public class MainForm extends javax.swing.JFrame {

    Administrator ulogovani;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani administrator: " + ulogovani);
        setTitle("Glavna forma");
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        cmbKategorijaMS = new javax.swing.JComboBox();
        cmbMedicinskoSredstvo = new javax.swing.JComboBox();
        txtCenaStavke = new javax.swing.JFormattedTextField();
        txtKolicina = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        txtDatumIsporuke = new javax.swing.JFormattedTextField();
        cmbBolnica = new javax.swing.JComboBox();
        lblUkupnaCena = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPorudzbina = new javax.swing.JMenu();
        miPretragaPorudzbine = new javax.swing.JMenuItem();
        jMenuBolnica = new javax.swing.JMenu();
        miNovaBolnica = new javax.swing.JMenuItem();
        miPretragaBolnica = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani administrator:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos porudzbine"));

        jLabel1.setText("Bolnica:");

        jLabel2.setText("Datum isporuke:");

        jLabel3.setText("Ukupna cena za ovu porudzbinu je:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos stavki porudzbine"));

        jLabel4.setText("Kategorija Med. Sredstva:");

        jLabel5.setText("Medicinsko sredstvo:");

        jLabel6.setText("Kolicina:");

        jLabel7.setText("Cena:");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        cmbKategorijaMS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategorijaMS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKategorijaMSItemStateChanged(evt);
            }
        });

        cmbMedicinskoSredstvo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMedicinskoSredstvo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMedicinskoSredstvoItemStateChanged(evt);
            }
        });

        txtCenaStavke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txtKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolicinaActionPerformed(evt);
            }
        });
        txtKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKolicinaKeyReleased(evt);
            }
        });

        jLabel8.setText("Spisak medicinskih sredstava za porudzbinu:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMedicinskoSredstvo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbKategorijaMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(82, 82, 82)
                                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtKolicina)
                                            .addComponent(txtCenaStavke))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKategorijaMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMedicinskoSredstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCenaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSacuvaj.setText("Sacuvaj porudzbinu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        txtDatumIsporuke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumIsporuke.setText("24.09.2024");
        txtDatumIsporuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumIsporukeActionPerformed(evt);
            }
        });

        cmbBolnica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblUkupnaCena.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblUkupnaCena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatumIsporuke)
                                    .addComponent(cmbBolnica, 0, 342, Short.MAX_VALUE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBolnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUkupnaCena)
                    .addComponent(btnSacuvaj))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnLogout.setText("Odjava");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenuPorudzbina.setText("Porudzbina");

        miPretragaPorudzbine.setText("Pretraga porudzbina");
        miPretragaPorudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaPorudzbineActionPerformed(evt);
            }
        });
        jMenuPorudzbina.add(miPretragaPorudzbine);

        jMenuBar1.add(jMenuPorudzbina);

        jMenuBolnica.setText("Bolnica");

        miNovaBolnica.setText("Dodaj novu bolnicu");
        miNovaBolnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaBolnicaActionPerformed(evt);
            }
        });
        jMenuBolnica.add(miNovaBolnica);

        miPretragaBolnica.setText("Pretraga bolnica");
        miPretragaBolnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaBolnicaActionPerformed(evt);
            }
        });
        jMenuBolnica.add(miPretragaBolnica);

        jMenuBar1.add(jMenuBolnica);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUlogovani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovani)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovaBolnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaBolnicaActionPerformed
        new FormNovaBolnica(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaBolnicaActionPerformed

    private void miPretragaBolnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaBolnicaActionPerformed
        new FormPretragaBolnica(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaBolnicaActionPerformed

    private void cmbKategorijaMSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKategorijaMSItemStateChanged

        if (cmbKategorijaMS.getSelectedItem() != null) {
            KategorijaMedicinskogSredstva kms = (KategorijaMedicinskogSredstva) cmbKategorijaMS.getSelectedItem();
            popuniMedicinskaSredstva(kms);
        }

    }//GEN-LAST:event_cmbKategorijaMSItemStateChanged

    private void txtKolicinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKolicinaKeyReleased

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {

            if (txtKolicina.getText().isEmpty()) {
                txtCenaStavke.setText("0.00");
                return;
            }

            int kolicina = Integer.parseInt(txtKolicina.getText());

            if (kolicina <= 0) {
                txtKolicina.setText("");
                return;
            }

            MedicinskoSredstvo ms = (MedicinskoSredstvo) cmbMedicinskoSredstvo.getSelectedItem();

            txtCenaStavke.setText(String.valueOf(ms.getCena() * kolicina));

        } else {
            txtKolicina.setText("");
            txtCenaStavke.setText("0.00");
        }

    }//GEN-LAST:event_txtKolicinaKeyReleased

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtKolicina.getText().isEmpty()
                || txtCenaStavke.getText().equals("0.00")) {
            JOptionPane.showMessageDialog(this, "Greska ... morate uneti kolicinu!");
            return;
        }

        MedicinskoSredstvo ms = (MedicinskoSredstvo) cmbMedicinskoSredstvo.getSelectedItem();
        int kolicina = Integer.parseInt(txtKolicina.getText());
        double cena = Double.parseDouble(txtCenaStavke.getText());

        StavkaPorudzbine sp = new StavkaPorudzbine(null, -1, kolicina, cena, ms);

        TableModelStavke tm = (TableModelStavke) tblStavke.getModel();
        tm.dodajStavku(sp);

        double ukupnaCena = Double.parseDouble(lblUkupnaCena.getText().replaceAll("[^0-9.]", ""));

        lblUkupnaCena.setText(String.valueOf(ukupnaCena + cena) + "rsd");

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavke tm = (TableModelStavke) tblStavke.getModel();

            StavkaPorudzbine sp = tm.getStavka(row);

            double ukupnaCena = Double.parseDouble(lblUkupnaCena.getText().replaceAll("[^0-9.]", ""));

            lblUkupnaCena.setText(String.valueOf(ukupnaCena - sp.getCenaStavke()) + "rsd");

            tm.obrisiStavku(row);

        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void cmbMedicinskoSredstvoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMedicinskoSredstvoItemStateChanged

        if (cmbMedicinskoSredstvo.getSelectedItem() != null) {

            txtKolicina.setText("");
            txtCenaStavke.setText("0.00");

        }

    }//GEN-LAST:event_cmbMedicinskoSredstvoItemStateChanged

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            if (txtDatumIsporuke.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Greska ... morate uneti datum isporuke!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumIsporuke = sdf.parse(txtDatumIsporuke.getText());

            double ukupnaCena = Double.parseDouble(lblUkupnaCena.getText().replaceAll("[^0-9.]", ""));
            Bolnica b = (Bolnica) cmbBolnica.getSelectedItem();
            TableModelStavke tm = (TableModelStavke) tblStavke.getModel();

            Porudzbina p = new Porudzbina(null, new Date(), datumIsporuke, 
                    ukupnaCena, b, ulogovani, tm.getLista());

            ClientController.getInstance().addPorudzbina(p);
            resetujFormu();
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana porudzbina.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void miPretragaPorudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaPorudzbineActionPerformed
        new FormPretragaPorudzbine(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaPorudzbineActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovani);
                new Login().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKolicinaActionPerformed

    private void txtDatumIsporukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumIsporukeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumIsporukeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbBolnica;
    private javax.swing.JComboBox cmbKategorijaMS;
    private javax.swing.JComboBox cmbMedicinskoSredstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBolnica;
    private javax.swing.JMenu jMenuPorudzbina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUkupnaCena;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaBolnica;
    private javax.swing.JMenuItem miPretragaBolnica;
    private javax.swing.JMenuItem miPretragaPorudzbine;
    private javax.swing.JTable tblStavke;
    private javax.swing.JFormattedTextField txtCenaStavke;
    private javax.swing.JFormattedTextField txtDatumIsporuke;
    private javax.swing.JTextField txtKolicina;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        popuniBolnice();
        popuniKategorije();
        txtCenaStavke.setEnabled(false);
        lblUkupnaCena.setText("0.00rsd");
        txtCenaStavke.setText("0.00");
        tblStavke.setModel(new TableModelStavke());
    }

    public void popuniBolnice() {
        try {
            ArrayList<Bolnica> bolnice = ClientController.getInstance().getAllBolnice();

            cmbBolnica.removeAllItems();

            for (Bolnica bolnica : bolnice) {
                cmbBolnica.addItem(bolnica);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniKategorije() {
        try {
            ArrayList<KategorijaMedicinskogSredstva> kategorije = ClientController.getInstance().getAllKategorijaMedicinskogSredstva();

            cmbKategorijaMS.removeAllItems();

            for (KategorijaMedicinskogSredstva kategorijaMS : kategorije) {
                cmbKategorijaMS.addItem(kategorijaMS);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniMedicinskaSredstva(KategorijaMedicinskogSredstva kms) {

        try {
            ArrayList<MedicinskoSredstvo> listaMS = ClientController.getInstance().getAllMedicinskoSredstvo(kms);

            cmbMedicinskoSredstvo.removeAllItems();

            for (MedicinskoSredstvo ms : listaMS) {
                cmbMedicinskoSredstvo.addItem(ms);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void resetujFormu() {
        txtDatumIsporuke.setText("");
        txtKolicina.setText("");
        txtCenaStavke.setText("0.00");
        lblUkupnaCena.setText("0.00rsd");
        TableModelStavke tm = (TableModelStavke) tblStavke.getModel();
        tm.ocistiTabelu();
    }

}
